name: hyper-realm

# Yahan hum saari modular files ko ek sath include kar rahe hain
include:
  - docker-compose.infra.yml
  - docker-compose.apps.yml
  - docker-compose.matrix.yml
  - docker-compose.local.yml    # 🚀 NAYI ENTRY: District Digital OS (Commerce, Services, Local Transit)

# Global network jo sab files share karengi
networks:
  hyper-realm-net:
    driver: bridge

# Global volumes ki mapping
volumes:
  hyper-id_pgdata:
  typesense_data:  
  qdrant_data:
  prometheus_data:
  grafana_data:
  redis_data:
  hyper_ceph_mock: